title: "CV of Konstantinos Zarkadoulas"
description: "Professional CV"
baseurl: "/cvzarkadoulas" # Set this to your repository name
url: "https://KonstantinosZarkadoulas.github.io" # Replace with your GitHub Pages URL
markdown: kramdown
theme: minima
